### ISSUE TITLE
Regression: GO 3.15 hangs when trying to play Binauralpipes samples

### ISSUE THREAD

**Issue by kerkovits** [GrandOrgue/grandorgue#1986]
# Steps to reproduce

1. Download one of the sample sets from https://binauralpipes.com/instrumente
2. Open GO 3.15 (I use the wx32 build on Linux, if it matters)
3. Play any note (you do not have to switch any stops) either by MIDI-message or simply by clicking on a key of any keyboard / pedal.

# What happens?

Infinite loop, process must be killed. No sound produced. Previous versions of GO work well.

**Comment by larspalo** [comment]
I can confirm this issue. GO crash with the following backtrace:

```
Thread 23 "GrandOrgue" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffbd7fa700 (LWP 48907)]
0x00005555557d6168 in GOSoundResample::ResamplingPosition::AvailableTargetSamples (this=0x55555655c6f4, endIndex=16420)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/GOSoundResample.h:105
105	               / m_FractionIncrement)
(gdb) bt
#0  0x00005555557d6168 in GOSoundResample::ResamplingPosition::AvailableTargetSamples(unsigned int) (this=0x55555655c6f4, endIndex=16420)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/GOSoundResample.h:105
#1  0x00005555557d8990 in GOSoundStream::ReadBlock(float*, unsigned int)
    (this=0x55555655c6a8, buffer=0x7fffbd7f7610, n_blocks=512)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/GOSoundStream.cpp:353
#2  0x00005555557bf93d in GOSoundEngine::ProcessSampler(float*, GOSoundSampler*, unsigned int, float)
    (this=0x7ffff1cc6300, output_buffer=0x7fffbd7f86e0, sampler=0x55555655c680, n_frames=512, volume=0.177827939)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/GOSoundEngine.cpp:236
#3  0x000055555581f413 in GOSoundGroupTask::ProcessList(GOSoundSamplerList&, bool, float*)
    (this=0x555556d1b2d0, list=..., toDropOld=true, output_buffer=0x7fffbd7f86e0)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/scheduler/GOSoundGroupTask.cpp:60
#4  0x000055555581f833 in GOSoundGroupTask::Run(GOSoundThread*)
    (this=0x555556d1b2d0, pThread=0x555556cbdcd0)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/scheduler/GOSou--Type <RET> for more, q to quit, c to continue without paging--
ndGroupTask.cpp:102
#5  0x00005555557b9798 in GOSoundThread::Entry() (this=0x555556cbdcd0)
    at /home/lars/Sources/github/grandorgue/src/grandorgue/sound/scheduler/GOSoundThread.cpp:35
#6  0x00007ffff7e10119 in GOThread::EntryPoint(GOThread*)
    (thread=0x555556cbdcd0)
    at /home/lars/Sources/github/grandorgue/src/core/threading/GOThread.cpp:35
#7  0x00007ffff7e10e36 in std::__invoke_impl<void, void (*)(GOThread*), GOThread*>(std::__invoke_other, void (*&&)(GOThread*), GOThread*&&)
    (__f=@0x55555686ee10: 0x7ffff7e100f6 <GOThread::EntryPoint(GOThread*)>)
    at /usr/include/c++/9/bits/invoke.h:60
#8  0x00007ffff7e10d96 in std::__invoke<void (*)(GOThread*), GOThread*>(void (*&&)(GOThread*), GOThread*&&)
    (__fn=@0x55555686ee10: 0x7ffff7e100f6 <GOThread::EntryPoint(GOThread*)>)
    at /usr/include/c++/9/bits/invoke.h:95
#9  0x00007ffff7e10cf5 in std::thread::_Invoker<std::tuple<void (*)(GOThread*), GOThread*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>)
    (this=0x55555686ee08) at /usr/include/c++/9/thread:244
#10 0x00007ffff7e10cac in std::thread::_Invoker<std::tuple<void (*)(GOThread*), GOThread*> >::operator()() (this=0x55555686ee08)
    at /usr/include/c++/9/thread:251
#11 0x00007ffff7e10c8c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(GOThread*), GOThread*> > >::_M_run() (this=0x55555686ee00)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/9/thread:195
#12 0x00007ffff6b79df4 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7079609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#14 0x00007ffff6866353 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

In this particular case I used the Kassel-Niederzwehren sample set.

**Comment by ruschbj** [comment]
Same here, but I get a crash-to-desktop using Obersuhl by binaural pipes. I'm attaching a procdump minidump
[GrandOrgue.exe_240823_021105.dmp](https://github.com/user-attachments/files/16725127/GrandOrgue.exe_240823_021105.dmp)

**Comment by oleg68** [comment]
Thank you for crash dumps. I managed to reproduce this crash  and I will fix it soon.
